version: 2.1
executors:
  runner:
    docker:
      - image: circleci/openjdk:11.0.6-jdk-stretch
    environment:
      JVM_OPTS: "-Xmx3g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
    working_directory: ~/repo
jobs:
  build:
    executor: runner
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - v1-gradle-cache-{{ checksum "build.gradle" }}
      - run: ./gradlew dependencies
      - save_cache:
          paths:
            - ~/.gradle/wrapper
          key: v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
      - save_cache:
          paths:
            - ~/.gradle/caches
          key: v1-gradle-cache-{{ checksum "build.gradle" }}
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    executor: runner
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          keys:
            - v1-gradle-wrapper-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
            - v1-gradle-cache-{{ checksum "build.gradle" }}
      - run:
          name: unit and integration tests
          command: ./gradlew check
      - store_test_results:
          path: build/test-results
workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test:
          requires:
            - build
